-- Создание таблицы Sensor
CREATE TABLE Sensor
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    name VARCHAR(30)
        CONSTRAINT sensor_name_check CHECK (LENGTH(name) >= 3)
);

-- Создание таблицы Measurement
CREATE TABLE Measurement
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    value     INTEGER
        CONSTRAINT measurement_value_check CHECK (value BETWEEN -100 AND 100),
    raining   BOOLEAN NOT NULL,
    sensor_id INTEGER
        REFERENCES Sensor (id)
)

